import random

quotes = ["EL CORAZÓN TIENE RAZONES QUE A RAZÓN IGNORA\n\t- BLAISE PASCAL", "DE LAS DIFICULTADES NACEN MILAGROS\n\t - JEAN DE LA BRUYÉRE","ESTAMOS HECHOS DE MIL OTROS, LA ILUSIÓN ES EL YO QUE PRETENDE SER SOLO UNO\n\t - JEAN-BERTRAND PONTALIS"]

print (quotes[random.randint(0, 2)])
